### ISSUE TITLE
Selenium and drop downs not working

### ISSUE THREAD

**Issue by goodmami** [delph-in/matrix#191]
**Migrated from Trac:**

> - Original: <http://lemur.ling.washington.edu/trac/matrix/ticket/713>
> - Reporter: goodmami
> - Created: 01/13/12 18:07:21
> - Updated: 01/13/12 18:07:21
> - Keywords: 
> - Notes:
>   - There may be formatting problems from the conversion
>   - Comments on tickets are *not* migrated! See the original issue.

Several of the web tests are failing. According to David Wax from the matrix-dev list, this is due to a change in the behavior in Selenium regarding drop-down selectors: "They 'fixed' drop down selects in a more recent version of the python Selenium webdriver, but it seems to have caused the previous code to stop working. I remember having issues getting it to work the first time; I've been working on this issue, but I can't say I've figured out how to get Selenium to select an option after focusing the drop downs to fill the options".

**Comment by ajcassell** [comment]
The web tests have since been fixed: https://github.com/delph-in/matrix/pull/730
