### ISSUE TITLE
Toolbox import not working for mcb

### ISSUE THREAD

**Issue by goodmami** [delph-in/matrix#256]
**Migrated from Trac:**

> - Original: <http://lemur.ling.washington.edu/trac/matrix/ticket/784>
> - Reporter: ebender
> - Created: 05/04/15 10:11:47
> - Updated: 05/04/15 10:11:47
> - Keywords: 
> - Notes:
>   - There may be formatting problems from the conversion
>   - Comments on tickets are *not* migrated! See the original issue.

See email from David to Emily on April 2015.

**Comment by emilymbender** [comment]
I can't in fact find anything relevant in email anymore. Closing this one as not enough info.
