### ISSUE TITLE
"other features" bug

### ISSUE THREAD

**Issue by goodmami** [delph-in/matrix#285]
**Migrated from Trac:**

> - Original: <http://lemur.ling.washington.edu/trac/matrix/ticket/823>
> - Reporter: ldermer
> - Created: 04/01/16 19:46:41
> - Updated: 04/01/16 19:46:41
> - Keywords: 
> - Notes:
>   - There may be formatting problems from the conversion
>   - Comments on tickets are *not* migrated! See the original issue.

You can create a verbal feature on the "other features" page, but when you try to apply it in the morphology section, it will tell you that it's for nouns only.

(Choices file attached. The feature is "evidential.")

**Comment by ajcassell** [comment]
This is no longer an issue. 
<img width="381" alt="Screen Shot 2024-10-02 at 8 06 09 PM" src="https://github.com/user-attachments/assets/41ab08ee-e2dd-48f3-92b8-c3ac9abf4cb5">
<img width="578" alt="Screen Shot 2024-10-02 at 8 05 56 PM" src="https://github.com/user-attachments/assets/12350c82-b35f-40a6-9f3f-5e871a7ff731">
