### ISSUE TITLE
mini-English PPP

### ISSUE THREAD

**Issue by goodmami** [delph-in/matrix#297]
**Migrated from Trac:**

> - Original: <http://lemur.ling.washington.edu/trac/matrix/ticket/839>
> - Reporter: ldermer
> - Created: 06/25/16 20:32:45
> - Updated: 06/25/16 20:32:45
> - Keywords: 
> - Notes:
>   - There may be formatting problems from the conversion
>   - Comments on tickets are *not* migrated! See the original issue.

The mini-English choices on the customization page gives me a python error if I load it up and go to the negation page, then go to any other page.

**Comment by ajcassell** [comment]
This cannot be reproduced so it appears to have been resolved.
