### ISSUE TITLE
Add trigger rule for copulas

### ISSUE THREAD

**Issue by goodmami** [delph-in/matrix#330]
**Migrated from Trac:**

> - Original: <http://lemur.ling.washington.edu/trac/matrix/ticket/895>
> - Reporter: kphowell
> - Created: 05/10/18 16:47:34
> - Updated: 05/10/18 16:47:34
> - Keywords: 
> - Notes:
>   - There may be formatting problems from the conversion
>   - Comments on tickets are *not* migrated! See the original issue.

lexical_items.py has the following comment:
# TODO: Add copula types to trigger.mtr

An example of a trigger rule for copulas is here: http://moin.delph-in.net/LkbGeneration

Examples in the matrix code can be found in lexical_items.py and clausalmods.py (search for trigger.add).

**Comment by ajcassell** [comment]
This has been resolved in https://github.com/delph-in/matrix/issues/712. However, the matrix code presently only generates trigger rules for copulas taking adjectival complements. This can be expanded for additional complement types.
