### ISSUE TITLE
Word order choices change on save & stay

### ISSUE THREAD

**Issue by goodmami** [delph-in/matrix#341]
**Migrated from Trac:**

> - Original: <http://lemur.ling.washington.edu/trac/matrix/ticket/908>
> - Reporter: ebender
> - Created: 04/25/19 17:55:33
> - Updated: 04/25/19 17:55:33
> - Keywords: 
> - Notes:
>   - There may be formatting problems from the conversion
>   - Comments on tickets are *not* migrated! See the original issue.

If we select "finite verb or auxiliary in second position, else free word order" and then "save & stay" it changes to "finite verb second, non-finite verb clause-finally".

I suspect this has something to do with one of the embedded clause libraries.

**Comment by ajcassell** [comment]
This is no longer an issue as "finite verb second, non-finite verb clause-finally" has been removed as an option in https://github.com/delph-in/matrix/pull/747
