### ISSUE TITLE
namespace protection in evidentials library

### ISSUE THREAD

**Issue by goodmami** [delph-in/matrix#345]
**Migrated from Trac:**

> - Original: <http://lemur.ling.washington.edu/trac/matrix/ticket/912>
> - Reporter: ebender
> - Created: 05/03/19 15:11:09
> - Updated: 05/03/19 15:11:09
> - Keywords: 
> - Notes:
>   - There may be formatting problems from the conversion
>   - Comments on tickets are *not* migrated! See the original issue.

The attached choices file shows that if a lexical rule is called "evidential" then the resulting grammar ends up with a cycle in it. This can probably be avoided by adding "evidential" as a protected name in validation.

**Comment by ajcassell** [comment]
@emilymbender I tried making a LRT named evidential as well as a noun PC named evidential and neither have issues generating or loading in the LKB. If I recall correctly from 567, the LKB would give a cycle warning/failure message when trying to load. For the LRT, these are all the instances of the term evidential in the output grammar.

<img width="408" alt="Screen Shot 2024-10-10 at 7 02 20 PM" src="https://github.com/user-attachments/assets/5856768a-e18e-45c5-b9b9-dda0ddcc9836">

**Comment by emilymbender** [comment]
Let's close this one as non-reproducible then.
