### ISSUE TITLE
Validation for inconsistent SPR values on noun types & supertypes

### ISSUE THREAD

**Issue by goodmami** [delph-in/matrix#365]
**Migrated from Trac:**

> - Original: <http://lemur.ling.washington.edu/trac/matrix/ticket/939>
> - Reporter: ebender
> - Created: 02/04/20 18:03:54
> - Updated: 02/04/20 18:03:54
> - Keywords: 
> - Notes:
>   - There may be formatting problems from the conversion
>   - Comments on tickets are *not* migrated! See the original issue.

If you give a pronoun or other det impossible noun type a supertype with non-impossible det customization produces a  grammar that won't compile. This should be caught in validation.

**Comment by ajcassell** [comment]
@emilymbender this appears to be resolved already. I made common-test noun type with obligatory determiner and had 1sg-pronoun with determiner impossible inherit from common-test and there is indeed an error message. 
<img width="731" alt="Screen Shot 2024-10-11 at 2 14 09 PM" src="https://github.com/user-attachments/assets/b503a6bc-f159-4853-9104-4b74b116fe5c">

<img width="837" alt="Screen Shot 2024-10-11 at 2 14 00 PM" src="https://github.com/user-attachments/assets/1952b0e2-937a-47aa-a291-a833e04f7c86">

**Comment by emilymbender** [comment]
Excellent.
