### ISSUE TITLE
subj-v-inv lex rule doesn't copy up MOD value

### ISSUE THREAD

**Issue by goodmami** [delph-in/matrix#370]
**Migrated from Trac:**

> - Original: <http://lemur.ling.washington.edu/trac/matrix/ticket/946>
> - Reporter: ebender
> - Created: 03/19/20 13:52:09
> - Updated: 03/19/20 13:52:09
> - Keywords: 
> - Notes:
>   - There may be formatting problems from the conversion
>   - Comments on tickets are *not* migrated! See the original issue.

subj-v-inv-lrule := cat-change-only-lex-rule & same-hc-light-lex-rule & same-posthead-lex-rule & constant-lex-rule &
  [ SYNSEM [ LKEYS #lkeys,
             LOCAL.CAT [ VAL [ COMPS < #subj . #comps >,
                               SUBJ < >,
                               SPR #spr,
                               SPEC #spec ],
                         MC na,
                         HEAD verb &
                              [ INV +,
                               MOD #mod, <<< ADD THIS
                                FORM #form ] ] ],
    DTR.SYNSEM [ LKEYS #lkeys,
                 LOCAL.CAT [ VAL [ SUBJ < #subj >,
                                   COMPS #comps,
                                   SPR #spr,
                                   SPEC #spec ],
                             HEAD verb &
                                  [ AUX +,
                                    MOD #mod, <<< ADD THIS
                                    FORM #form ] ] ] ].

**Comment by ajcassell** [comment]
Closed wth PR #750
