### ISSUE TITLE
User shouldn't have to move or remove grammars

### ISSUE THREAD

**Issue by goodmami** [delph-in/matrix#388]
**Migrated from Trac:**

> - Original: <http://lemur.ling.washington.edu/trac/matrix/ticket/33>
> - Reporter: sfd
> - Created: 11/11/08 19:19:36
> - Updated: 02/13/12 13:10:56
> - Keywords: 
> - Notes:
>   - There may be formatting problems from the conversion
>   - Comments on tickets are *not* migrated! See the original issue.

If you run a unit test and it fails in such a way that it leaves a grammar behind in the grammars directory, the next time you run you get an error message like:

case-split-v...Move /home/sfd/matrix/customize/unit-tests/grammars/case-split-v, it is in the way

I think that directory should be removed automatically if you run the unit tests again.  There should at least be a "force" flag somewhere.  Deleting the grammars by hand is troublesome.

**Comment by olzama** [comment]
Still relevant?

**Comment by goodmami** [comment]
Nope. This hasn't been the case in a while.
