### ISSUE TITLE
add-unit-test should either skip or escape quotation marks

### ISSUE THREAD

**Issue by goodmami** [delph-in/matrix#389]
**Migrated from Trac:**

> - Original: <http://lemur.ling.washington.edu/trac/matrix/ticket/37>
> - Reporter: antske
> - Created: 12/12/08 13:55:50
> - Updated: 12/12/08 13:55:50
> - Keywords: 
> - Notes:
>   - There may be formatting problems from the conversion
>   - Comments on tickets are *not* migrated! See the original issue.

**Comment by ajcassell** [comment]
@emilymbender I don't see anywhere in the code with functionality to add unit tests. I have been handwriting them, not using some command. I think this can be closed.

**Comment by emilymbender** [comment]
What was the content of this ticket? I don't see anything except that it was imported.

At any rate, are you talking about the tests here?
https://github.com/delph-in/matrix/tree/trunk/tests/unit

**Comment by ajcassell** [comment]
There is no content to the ticket. I just based my investigation off the issue title. Yes, those are the unit tests I am referring to. I don't see a command anywhere to programmatically add one such as "add-unit-test".

**Comment by emilymbender** [comment]
Got it -- closing the issue.
