### ISSUE TITLE
Subpage quick links

### ISSUE THREAD

**Issue by goodmami** [delph-in/matrix#402]
**Migrated from Trac:**

> - Original: <http://lemur.ling.washington.edu/trac/matrix/ticket/638>
> - Reporter: goodmami
> - Created: 06/17/10 11:40:09
> - Updated: 06/17/10 11:40:09
> - Keywords: 
> - Notes:
>   - There may be formatting problems from the conversion
>   - Comments on tickets are *not* migrated! See the original issue.

As the amount of interacting elements among separate subpages increases, so does the need to quickly flip back and forth between the subpages. Submitting, returning to the main page, and clicking the next subpage is too cumbersome. Some ideas are:

Floating menu with links to subpages
Separate frame with links
Buttons (e.g. "submit and go to X page") for most common use cases

Most appealing is probably the floating menu, if it's within our web development capabilities and not too distracting.

**Comment by ajcassell** [comment]
This can be closed now that we have the sidebar panel of links.
