### ISSUE TITLE
Main page choice summary replaces values with matrixdef friendly names

### ISSUE THREAD

**Issue by goodmami** [delph-in/matrix#413]
**Migrated from Trac:**

> - Original: <http://lemur.ling.washington.edu/trac/matrix/ticket/701>
> - Reporter: goodmami
> - Created: 10/01/11 12:10:26
> - Updated: 10/01/11 12:10:26
> - Keywords: 
> - Notes:
>   - There may be formatting problems from the conversion
>   - Comments on tickets are *not* migrated! See the original issue.

Load up the questionnaire, set the value of a choice (e.g. language name) to something like "a", "omni", or "other", and when you submit and drop down the choices summary for that page from the main page, the it will display the friendly name (like "Asyndeton", "Omnisyndeton", or  "Some other form").

**Comment by ajcassell** [comment]
@emilymbender I don't think this is reproducible. I tried all three of the above for language name and they were all included in the choices correctly. For example:

![Screen Shot 2024-10-17 at 6 31 45 PM](https://github.com/user-attachments/assets/bcb59e03-8e7d-4f31-a1d1-216c9a24ce51)

<img width="342" alt="Screen Shot 2024-10-17 at 6 31 34 PM" src="https://github.com/user-attachments/assets/3bf196cb-aa69-4663-9d5c-fef6048dbecf">

**Comment by emilymbender** [comment]
Seems like it was fixed then!
