### ISSUE TITLE
need to add error logging in choices.py

### ISSUE THREAD

**Issue by goodmami** [delph-in/matrix#436]
**Migrated from Trac:**

> - Original: <http://lemur.ling.washington.edu/trac/matrix/ticket/843>
> - Reporter: ldermer
> - Created: 02/22/17 17:56:46
> - Updated: 02/22/17 17:56:46
> - Keywords: 
> - Notes:
>   - There may be formatting problems from the conversion
>   - Comments on tickets are *not* migrated! See the original issue.

There's lots of spots where errors should be logged in choices.py. These are mostly marked with a # TODO as far as I could see.

**Comment by ajcassell** [comment]
Completed with PR #753
