### ISSUE TITLE
Confusing errors in regression-test-add

### ISSUE THREAD

**Issue by goodmami** [delph-in/matrix#440]
**Migrated from Trac:**

> - Original: <http://lemur.ling.washington.edu/trac/matrix/ticket/848>
> - Reporter: cmc3c
> - Created: 04/09/17 12:21:56
> - Updated: 04/12/17 19:27:08
> - Keywords: 
> - Notes:
>   - There may be formatting problems from the conversion
>   - Comments on tickets are *not* migrated! See the original issue.

Most of the OS interaction in `regression-test-add` is handled by `add_regression_test.py`, but the error handling is mostly confined to a trap in `matrix.py` on `ValueError` and `OSError`. The error message on `OSError` says the problem is "Most likely Subversion is not installed", but it seems like the vast majority of potential problems are path errors.

Better path handling (~~#847~~ #439) would make errors less likely; this ticket is specifically to address better error handling and messaging.

*edit: Trac issue numbers are not the same as GitHub issue numbers.*

**Comment by olzama** [comment]
Still relevant?

**Comment by goodmami** [comment]
That code in matrix.py is gone. I think this is mostly not relevant. If we find improper error messages from rtest.py in the future, let's open a new issue.

**Comment by goodmami** [comment]
I am now seeing a similar error on 'customize'. I opened #487 as a separate issue because, while it has similar symptoms, it is a different problem.
