### ISSUE TITLE
regression-test-add fails when choices file has iso-code

### ISSUE THREAD

**Issue by goodmami** [delph-in/matrix#444]
**Migrated from Trac:**

> - Original: <http://lemur.ling.washington.edu/trac/matrix/ticket/862>
> - Reporter: cmc3c
> - Created: 12/14/17 19:32:26
> - Updated: 12/14/17 19:32:26
> - Keywords: 
> - Notes:
>   - There may be formatting problems from the conversion
>   - Comments on tickets are *not* migrated! See the original issue.

The symptom is the same as when ACEROOT or CUSTOMIZATIONROOT is misconfigured: 

IOError: [Errno 2] No such file or directory: '<gmcspath>/regression_tests/home/gold/<lang-name>/item'

This appears to be a bug (or at least undocumented behavior) in the interaction between customization.py and add_regression_test.sh.

Here’s what I figured out:

1. Customizing a choices file to a non-existing directory creates that directory and builds the customized grammar in it.
2. Customizing a choices file to an existing directory creates a new directory to hold the customized grammar; that new directory is named using the iso-code from the choices file if set, otherwise using the language from the choices file.
3. add_regression_test.sh ensures the directory gmcs/regression_tests/scratch/grammars/ exists.
4. add_regression_test.sh calls customize with `gmcs/scratch/grammars/ as the output directory.

The result is that if you set an iso-code in your choices file, then the generated grammar will be named with it. Unfortunately, everything else in the add_regression_test process is using the language from the choices, so ace will not be able to find the generated grammar.

The simple workaround is not to set an iso-code for regression tests based on languages that have them; there’s also a one-line change to add_regression_test.sh that probably fixes it.

**Comment by olzama** [comment]
Is this one still relevant?

**Comment by goodmami** [comment]
Don't think so. We now customize directly to a directory instead of using language name or iso code. I'll close it.
