### ISSUE TITLE
Auxiliary Features Dropdown

### ISSUE THREAD

**Issue by goodmami** [delph-in/matrix#445]
**Migrated from Trac:**

> - Original: <http://lemur.ling.washington.edu/trac/matrix/ticket/863>
> - Reporter: kphowell
> - Created: 01/12/18 13:56:10
> - Updated: 01/12/18 13:56:10
> - Keywords: 
> - Notes:
>   - There may be formatting problems from the conversion
>   - Comments on tickets are *not* migrated! See the original issue.

The Auxiliary features dropdown only populates with verbal features, so it is not possible to specify features on the subject. Emily believes this should be possible.

**Comment by ajcassell** [comment]
This is no longer an issue.
<img width="753" alt="Screen Shot 2024-10-03 at 6 54 47 PM" src="https://github.com/user-attachments/assets/685978f5-174e-4d9d-977c-0af8a3053b50">
