### ISSUE TITLE
arg-comp-aux missing unexpressed on complement's subject

### ISSUE THREAD

**Issue by goodmami** [delph-in/matrix#453]
**Migrated from Trac:**

> - Original: <http://lemur.ling.washington.edu/trac/matrix/ticket/887>
> - Reporter: ebender
> - Created: 02/16/18 10:58:56
> - Updated: 02/16/18 10:58:56
> - Keywords: 
> - Notes:
>   - There may be formatting problems from the conversion
>   - Comments on tickets are *not* migrated! See the original issue.

The arg-comp-aux type should say unexpressed about it's verbal complement's subject in order not to break lexical threading of non-local features.

**Comment by ajcassell** [comment]
EMB: "Lexical threading is gone, actually, so I think this one is moot."
