### ISSUE TITLE
Rtest cosmetics

### ISSUE THREAD

**Issue by olzama** [delph-in/matrix#479]
I wonder if it makes sense to make the "progress bar" that rtest currently prints out, shorter? As it is, it makes the output longer than the default size of the terminal on 13'' monitors (at least on my 13" monitor). Of course it is possible to resize the terminal but that's not really the most convenient thing to have to do often (somehow).

**Comment by olzama** [comment]
<img width="576" alt="Screen Shot 2020-07-17 at 12 15 02 PM" src="https://user-images.githubusercontent.com/10963114/87823204-bb4eba00-c827-11ea-8011-a109234cce7f.png">

**Comment by goodmami** [comment]
I came across this as well. I had a couple ideas for making this output prettier beyond just the progress bar width, too:

* One progress bar for the overall progress, since for most test suites you don't actually see the progress until it's done.
* One line per test, rather than 2 or 3

Something like this:

```
Cree (106/106)                                                                              PASS
Dyirbal (44/44)                                                                             PASS
Finnish (36/36)                                                                             PASS
Fore (76/76)                                                                                PASS
|####-               | 4/478 || Customizing: German
```

**Comment by olzama** [comment]
This looks nice and makes a lot of sense! (Hopefully still with some green/red/brown color for PASS/ERROR/FAIL and with the summary at the end.) But something like this I think I won't work on right now; it would be distracting. Maybe some time later. The length of the bar issue I could just fix now :).

**Comment by goodmami** [comment]
No worries. I could probably do this myself.

**Comment by goodmami** [comment]
Ok I looked into what was happening, and the progress bar is actually printed by PyDelphin, not rtest.py, so it's not straightforward to fix the width. I'll see if I can turn off the PyDelphin one and just use our own.
