### ISSUE TITLE
Add better support for "skipped" regression tests

### ISSUE THREAD

**Issue by goodmami** [delph-in/matrix#497]
There is some need to allow known-failing tests to be skipped (see #494). We can remove the entries for the tests from `tests/regression/regression-test-index`, as is done for Sahaptin, but this index also contains comments, so deleting them would lose information. We could create a secondary index of skipped tests, or we could somehow mark tests in the index to be skipped (similar to pytest's [mark.skip](https://docs.pytest.org/en/stable/skipping.html) functionality). For the latter option, how about a `!` before the entry?

```
infostr-foc-adp-after-noun=infostr
!infostr-foc-affix-after-noun=infostr
```

Here the second test is skipped.

The other part of this issue is finding a better way to report that tests were skipped. Tests with missing files (txt-suites, skeletons, etc.) or entries in this file would be marked as incomplete, and those with `!` in the index would be reported as skipped.

**Comment by olzama** [comment]
Oh I like that!! I was going to suggest an rtest option which shows all the skipped ones but this is even better (and for the command to work, something like this would be needed anyway).

**Comment by goodmami** [comment]
Ok I'll submit a separate PR for this.
