### ISSUE TITLE
Rtest: need help debugging an error

### ISSUE THREAD

**Issue by olzama** [delph-in/matrix#501]
I am having the following issue with running rtest on one of my wh test (so, you'd need to check out my **merge-wh** branch to see this).

The test in question is **wh-yux-dev**. Right now it is skipped (has a ! in the index).

If you enable it again (remove the ! in the regression-test-index), you will see that it seems to go into something like an infinite loop (which is why I disabled it for a while, when I first started merging my library):

```
(pydelphin-1.4.0) (base) MurkinPro:matrix-git olzama$ ./rtest.py wh-yux-dev
^CProcess ForkPoolWorker-4:
Process ForkPoolWorker-3:
Process ForkPoolWorker-2:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/olzama/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/Users/olzama/anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/olzama/anaconda3/lib/python3.7/multiprocessing/pool.py", line 110, in worker
    task = get()
  File "/Users/olzama/anaconda3/lib/python3.7/multiprocessing/queues.py", line 351, in get
    with self._rlock:
  File "/Users/olzama/anaconda3/lib/python3.7/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
Traceback (most recent call last):
KeyboardInterrupt
  File "/Users/olzama/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/Users/olzama/anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/olzamaTraceback (most recent call last):
  File "/Users/olzama/anaconda3/lib/python3.7/multiprocessing/pool.py", line 733, in next
    item = self._items.popleft()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./rtest.py", line 781, in <module>
    exit_status = main(args)
  File "./rtest.py", line 119, in main
    return args.function(args)
  File "./rtest.py", line 144, in run_tests
    totals = _accumulate(results, total)
  File "./rtest.py", line 212, in _accumulate
    for i, (name, result, logpath) in enumerate(results, 1):
  File "/Users/olzama/anaconda3/lib/python3.7/multiprocessing/pool.py", line 737, in next
    self._cond.wait(timeout)
  File "/Users/olzama/anaconda3/lib/python3.7/threading.py", line 296, in wait
    waiter.acquire()
KeyboardInterrupt
(pydelphin-1.4.0) (base) MurkinPro:matrix-git olzama$ 
```

But trying to debug it, I get an error: 

```
=====
Traceback (most recent call last):
  File "/Users/olzama/Research/matrix-git/rtest.py", line 190, in _run_test
    _process(name, dat, prof, logf)
  File "/Users/olzama/Research/matrix-git/rtest.py", line 616, in _process
    process(dat, prof, stderr=logf, report_progress=False)
TypeError: process() got an unexpected keyword argument 'report_progress'
```

I don't seem to be able to step into the `report` function, so, I can't really figure out what's going on. Any ideas? @goodmami

**Comment by olzama** [comment]
Actually, the descriprion above was with a slightly out-of-date version of rtest. I now merged in the current trunk version, and now, I am not sure what I am doing wrong, but the test gets skipped even though I deleted the ! in front of it in the index?..

**Comment by olzama** [comment]
OK, that was just some weirdness with the index file version; I now confirmed that the behavior is the same (as described in the first post) with the latest changes in rtest. 

I have pydelphin-1.4.0.

**Comment by goodmami** [comment]
Why do you suspect that rtest.py is getting into an infinite loop? It looks like the grammar is underconstrained and ACE is spinning. I confirmed this by running individual sentences through ACE without using rtest or PyDelphin at all, and most just exit after consuming the available RAM:

```console
$ ace -g yux.dat <<< "kin-ek met-gele edies-l"
NOTE: terminating search, too much RAM
NOTE: 0 readings, added 1625 / 1595 edges to chart (190 fully instantiated, 15 actives used, 180 passives used)	RAM: 1230030k
SKIP: kin-ek met-gele edies-l


NOTE: parsed 0 / 1 sentences, avg 1230030k, time 4.42454s
```

The last two items, at least, take longer to consume the RAM, and when they finally do, ACE prints the handful of analyses it reached before dying, but then doesn't seem to exit (I waited about 5 minutes after it claimed to run out of RAM before killing the process).

So the first error message pasted above is uninformative; it is just where in the process it was when you Ctrl-C'd out. Debugging in PyCharm or similar probably wouldn't help much because it won't return from the call to ACE (or it just takes a long time), so it won't reach the `report` function in reasonable time.

The second error you noted indicates that you have a PyDelphin version < 1.4.0 in the active environment when you were debugging. That `report_progress` parameter was added in 1.4.0.

Finally, note that you do not have to modify `regression-test-index` to enable the skipped tests, as that's what the `--skipped` option now does:

```console
$ grep wh-yux-dev tests/regression/regression-test-index 
!wh-yux-dev=Small grammar of Yukaghir featuring morphological marking of questions and focus-person split.
$ python rtest.py wh-yux-dev --skipped
```

**Comment by olzama** [comment]
Oh, I see. I thought it was rtest because this test used to work before. But of course this could be some other change which happened during merge.

I most certainly have pydelphin 1.4.0 when I run rtest in the terminal but perhaps the environment in pycharm is wrong...

**Comment by goodmami** [comment]
>  but perhaps the environment in pycharm is wrong...

I'm teaching a course introducing Python and we're using Visual Studio Code. We have the same problem with the editor not selecting the right environment, and it's been very confusing for these students new to programming :P Sorry I don't know anything about PyCharm.

**Comment by olzama** [comment]
Well, I think I can testify to it being confusing not only to those new to programming. I think it is simply confusing :). Or certainly to anyone to whom assembly hasn't been central to what they have been doing during all those years.

I verified that my current PyCharm environment is 1.4.0:

<img width="982" alt="Screen Shot 2020-08-21 at 7 22 53 PM" src="https://user-images.githubusercontent.com/10963114/90946667-e9558a00-e3e3-11ea-8292-febcc24cbc1d.png">

so I don't know what's going on in that respect...

**Comment by goodmami** [comment]
Yes, sorry, I meant that it's confusing in general (for me, too), but especially for those new to programming.

**Comment by olzama** [comment]
Thanks for the debugging strategy! I will look on Monday!
