### ISSUE TITLE
Determiner inflection questionnaire has some unnecessary stuff in it.

### ISSUE THREAD

**Issue by olzama** [delph-in/matrix#520]
I think you don't want this `toggle_element.call(this, 'adj-pc{i}_lrt{j}_adj_pc_note', 'on', ['subj', 'mod'])` call here, that's for showing the switching type LRTs message when defining a switching type adjective.

_Originally posted by @dantiston in https://github.com/delph-in/matrix/pull/518#discussion_r489919839_

**Comment by olzama** [comment]
This can't be properly tested until the website starts working with the python3 version of the Matrix.

**Comment by ajcassell** [comment]
This has been completed already. Closing!

<img width="1102" alt="Screen Shot 2024-09-27 at 5 12 59 PM" src="https://github.com/user-attachments/assets/f8842bcb-1b96-4580-8d3c-bca2323eca5c">
