### ISSUE TITLE
rtest doesn't ignore .DS_store

### ISSUE THREAD

**Issue by olzama** [delph-in/matrix#522]
I am not sure this should be dealt with at the level of rtest, or perhaps it is my own responsibility to make sure .DS_store doesn't appear where I don't want it? But I don't know how to do that, and I am sure most people don't either. Could we make it so rtest --clean deletes .DS_store or/and rtest doesn't try to treat it as a test if it is there?

I realize that .DS_store being a OSX thing might make dealing with it on the level of rtest unappealing.

**Comment by goodmami** [comment]
> Could we make it so rtest --clean deletes .DS_store

I don't think that's a good idea. `--clean` is meant to only delete rtest temporary files, not system files.

> or/and rtest doesn't try to treat it as a test if it is there?

Yes, we already ignore `README` and `README.md`, so we could add `.DS_Store` or perhaps anything starting with a dot. It might even be better to use `.gitignore`, but now I notice that our `.gitignore` file is a bit sparse.

**Comment by olzama** [comment]
Hmm, but gitignore wouldn't take care of the problem locally, would it? I mean, I am already not adding .DS_store to the repo, obviously (so I have it in my global ignore list), but I still need to take care of .DS_Store manually every time it creeps in locally.

**Comment by goodmami** [comment]
I mean that rtest would read `.gitignore`. Just an option.

**Comment by olzama** [comment]
Ooh I see, yeah, that makes sense! And we could add more things there (not anything extraordinary, but if we are to add something like .DS_Store to some list that rtest is aware about, might as well add it to gitignore).

**Comment by goodmami** [comment]
In the end I decided not to use `.gitignore` because we would need to do glob (or fnmatch) pattern matching on the files, which makes it complicated, and also it might ignore things we care about for test discovery because `.gitignore` ignores the directories for grammars, etc.
