### ISSUE TITLE
Some choices files load fine, some do not (questionnaire)

### ISSUE THREAD

**Issue by olzama** [delph-in/matrix#552]
Related to #550.

Currently, the minimal grammar, Mini English, and Maltese sample choices load fine into the new questionnaire. However the other choices files (Japanese, Sahaptin, as well as all regression choices which I tried) lead immediately to an Internal Server Error with no python error on the surface. @bmgraves also says he could not identify a specific python error leading to the server error as of yet, apart from the fact that some character cannot be decoded.

**Comment by emilymbender** [comment]
Hmm ... are there any commonalities in the version number for those that work v. those that don't? (If so, the problem might be in the uprevving somewhere.)

**Comment by bmgraves** [comment]
Just to keep all information together, specifically the errors i see is a generic apache:

> AH02429: Response header name '<!--' contains invalid characters, aborting request"

Which doesn't really give us much to go on. I've done a test run of going through deffile.py and looking for every line that opens a text file to append "encoding="utf-8"" to it, but that hasn't changed anything. I've since backed those changes out though.

**Comment by olzama** [comment]
> Hmm ... are there any commonalities in the version number for those that work v. those that don't? (If so, the problem might be in the uprevving somewhere.)

Well, the ones which break are the ones which contain unicode characters. That's the most likely explanation, I think. I did look at the uprevving and there doesn't seem anything there that has to do with encoding, at least not on the first glance... There was a bug in uprevving which would lead to an invalid Japanese choices set, but I believe it is unrelated (and there wasn't such an issue with e.g. Sahaptin).

**Comment by olzama** [comment]
Although... why would the regression choices not load properly then. Those do not always contain unicode... hmm.

**Comment by olzama** [comment]
Could the problem be hidden here? (I am not sure; can't tell yet. Maybe unlikely because this is not directly at the interface with the website.)

```
        if choices_file is not None:
            try:
                f = choices_file
                if type(choices_file) == str:
                    f = open(choices_file, 'r', encoding='utf-8')
                f.seek(0)
                lines = [line.strip() for line in f if line.strip()]
                self.load_choices(lines)
                if type(choices_file) == str:
                    f.close()
            except IOError:
                pass  # TODO: we should really be logging these
```

Note the `pass` statement.

**Comment by olzama** [comment]
> Hmm ... are there any commonalities in the version number for those that work v. those that don't? (If so, the problem might be in the uprevving somewhere.)

The sample ones which do not load properly are below version 22. Maltese is 22 and it loads. However this does not explain all of the regression ones, which as far as I can tell all fail! But perhaps it is unrelated?..

**Comment by olzama** [comment]
Possibly related/helpful? https://stackoverflow.com/questions/9322410/set-encoding-in-python-3-cgi-scripts

In particular:

> in a CGI script you need to write to sys.stdout and you can use print() to do it; but a CGI script process in Apache has no locale environment settings - they are not part of the CGI specification; therefore the sys.stdout encoding defaults to ANSI_X3.4-1968 - in other words, ASCII; if you try to print() a string that contain non-ASCII characters to sys.stdout you'll get "UnicodeEncodeError: 'ascii' codec can't encode character...: ordinal not in range(128)"

Their suggestion is:

> a simple solution is to pass the Apache process's LANG environment variable through to the CGI script using Apache's mod_env PassEnv command in the server or virtual host configuration: PassEnv LANG; on Debian/Ubuntu make sure that in /etc/apache2/envvars you have uncommented the line ". /etc/default/locale" so that Apache runs with the system default locale and not the C (Posix) locale (which is also ASCII encoding)

**Comment by bmgraves** [comment]
This may be closable. ill wait for @olzama to test as well, but i found the error on the apache side that was sending the wrong encoding to python.

**Comment by olzama** [comment]
The sample choices are now working (yay!!) but the regression choices files which are loaded by Choices file --> Upload choices file buttons still lead to the same error :(. Maybe has to do with the button?

Update: double checked that it is something to do with the button. The same Japanese sample choices leads to the error if uploaded through the button "Upload choices file" rather than by clicking on the link.

**Comment by olzama** [comment]
I will open a new issue for the button.
