### ISSUE TITLE
The % character in customization system

### ISSUE THREAD

**Issue by olzama** [delph-in/matrix#561]
https://delphinqa.ling.washington.edu/t/lkb-fos-in-identifiers/612/8

**Comment by goodmami** [comment]
In case the link goes down, a brief summary: The `%` character was declared invalid in TDL identifiers, and some TDL parsers (LKB-FOS, recent versions of the LKB, PyDelphin) enforced this situation. Others (older versions of the LKB, ACE, possibly PET and agree (not tested)) did not explicitly forbid them. The Matrix used `%` for pseudo percent-encoding of other invalid TDL characters in identifiers, so now customized grammars might not load with the more strict parsers.

**Comment by goodmami** [comment]
Closed by aadb1d935db3211ee7645439e28f2bbf41a24da8
