### ISSUE TITLE
matrix.tdl~ and roots.tdl~ in online Matrix site.

### ISSUE THREAD

**Issue by emilymbender** [delph-in/matrix#562]
Grammars customized with the current version posted to the main site include two emacs backup files: matrix.tdl~ and roots.tdl~. These should be removed. Even better would be tweaks to the vivification process to make sure that no files with ~ or # get uploaded.

**Comment by olzama** [comment]
Yes, I noticed that, too. Thanks for filing this; I thought I had filed it but I suppose I forgot. 

Interestingly, we do not have those files in the repository. It is a bit of a mystery to me where they come from. They must live on the server, but how would they end up there if this is a fresh installation... Hmm.

**Comment by olzama** [comment]
They were on the server (I suppose customize/ is not a fresh location). I removed them.

**Comment by olzama** [comment]
Added *~ to the `install' script ignore list.
