### ISSUE TITLE
Inflectional rules being instantiated in rules.tdl (COORD library)

### ISSUE THREAD

**Issue by lizcconrad** [delph-in/matrix#565]
In the coordination library, inflectional rules are being instantiated both in irules.tdl and rules.tdl. The following snippet shows one such rule from iso.tdl:

```
n25-bottom-coord-rule := infl-bottom-coord-rule &
  [ SYNSEM.LOCAL.COORD-STRAT "25",
    SYNSEM.LOCAL.COORD-REL.PRED "_and_coord_rel",
    DTR.SYNSEM.LOCAL.CAT.HEAD noun ].
```

The following appears in `irules.tdl` as intended:

```
n25-bottom :=
  %prefix (* go-)
  n25-bottom-coord-rule.
```

...but the following is also in rules.tdl, which should not be happening since the appropriate rule was already instantiated in irules.tdl:

```
n25-bottom-coord := n25-bottom-coord-rule.
```

**Comment by ajcassell** [comment]
This fix was accomplished in https://github.com/delph-in/matrix/commit/54ef66875f39760471be8eca8929b729a032842c. Closing the issue.
