### ISSUE TITLE
V2 choice displays funny on word order page

### ISSUE THREAD

**Issue by emilymbender** [delph-in/matrix#573]
It seems like both "finite verb or auxiliary in second position, else free word order" and 
"finite verb second, non-finite verb clause-finally" are mapped to:

word-order=v2

in the questionnaire, which can't be right.

**Comment by ajcassell** [comment]
@emilymbender They are indeed both mapped to the v2 word order selection. Do you have a suggestion for what this should be instead? Is there another value that can be put here or is there more work required throughout the matrix to handle whichever of these is not v2?

<img width="975" alt="Screen Shot 2024-10-05 at 4 21 17 PM" src="https://github.com/user-attachments/assets/4a897eb5-6509-40c6-b1c7-e1d861521c5e">

**Comment by emilymbender** [comment]
I don't know off the top of my head -- the thing would be to look through the word order library to see if there is another option already.

**Comment by ajcassell** [comment]
There is not another option. What I am seeing is that the first 6 word orders, V-final, V-initial, and free are handled first. Then if word-order = 'v2', some phrase rules are added and then immediately following this, there are `rules shared among free and v2` so my instinct is to believe that maybe that last option is not accounted for.

**Comment by emilymbender** [comment]
I think the best path is then to remove the last option, since it's not meaningful.
