### ISSUE TITLE
Validation error with auxiliaries + case

### ISSUE THREAD

**Issue by emilymbender** [delph-in/matrix#574]
In a grammar with no case system, a choice like:
  aux2_subj=np-comp-case

... will put a constraint referencing CASE on the auxiliary leading to a grammar that doesn't load.

This could be caught in validation.

**Comment by ajcassell** [comment]
@emilymbender I believe this is a duplicate issue and was handled in this PR: https://github.com/delph-in/matrix/pull/759

**Comment by emilymbender** [comment]
Agreed.
