### ISSUE TITLE
basic-determiner-lex has LTOP pointing to LBL

### ISSUE THREAD

**Issue by emilymbender** [delph-in/matrix#575]
... where determiners shouldn't have their LTOP pointing to anything.

**Comment by ajcassell** [comment]
<img width="590" alt="Screen Shot 2024-10-31 at 8 29 55 PM" src="https://github.com/user-attachments/assets/84fe5da8-946e-4b3a-a5f6-489654235bef">

@emilymbender I don't see LBL mentioned here? no-ltop-lex-item also does not reference LBL anywhere.

**Comment by emilymbender** [comment]
Let's assume this has been fixed then.
