### ISSUE TITLE
Prompting for PRED values for wh pronouns

### ISSUE THREAD

**Issue by emilymbender** [delph-in/matrix#577]
Based on the experience in this year's 567, it's not obvious that something like _thing_n_rel is expected rather than _what_n_rel, in defining a wh pronoun.

**Comment by ajcassell** [comment]
@emilymbender what would be a reasonable "prompt" here?

**Comment by emilymbender** [comment]
Could be something like: "Use _thing_n_rel, _person_n_rel, _place_n_rel or similar"
