### ISSUE TITLE
Extraneous constraints on RELS.LIST in norm-adposition-lex

### ISSUE THREAD

**Issue by emilymbender** [delph-in/matrix#586]
This definition of norm-adposition-lex (from a student grammar, but apparently produced by the customization system) is placing constraints on CONT.RELS.LIST instead of LKEYS.KEYREL, even though the two are already identified (in norm-sem-lex-item or a supertype thereof). Furthermore, that existing identity makes the #pred identity superfluous. Supertypes should also already handle the #ind2 identity and I'd think the type (event) of ARG0.

norm-adposition-lex := norm-sem-lex-item & no-hcons-lex-item & basic-intersective-mod-lex & non-local-none-lex-item &
  [ ARG-ST < #comp >,
    SYNSEM [ LKEYS.KEYREL arg12-ev-relation &
                          [ PRED #pred,
                            ARG0 #ind2,
                            ARG1 #ind ],
             L-QUE #lque,
             LOCAL [ CONT [ HOOK [ XARG #ind2,
	     	     	    	  INDEX #ind2 ],
			  RELS.LIST < [ PRED #pred,
                                        ARG0 event,
                                        ARG1 event-or-ref-index ] > ],
                     CAT [ WH.BOOL -,
                           VAL [ SPR < >,
                                 SPEC < >,
                                 SUBJ < [ LOCAL [ CAT cat-sat &
                         	      	  	    	    [ VAL [ SPR < >,
                                 			    COMPS < > ],
                          				     HEAD noun ],
					          CONT.HOOK.INDEX #ind2 ] ] >,
                                 COMPS < #comp &
                                         [ L-QUE #lque,
                                           LOCAL [ CAT [ HEAD noun,
                                                         VAL.SPR < > ],
                                                   CONT.HOOK.INDEX #ind ] ] > ],
                           HEAD adp &
                                [ MOD < [ LOCAL.CAT [ VAL.SPR cons,
                                                      WH.BOOL -,
                                                      HEAD.AUX - ] ] > ] ] ] ] ].

**Comment by ajcassell** [comment]
@emilymbender Is the objective here then to just remove the PRED, ARG0, and ARG1 from RELS.LIST and PRED from LKEYS.KEYREL?

**Comment by emilymbender** [comment]
The identities listed in the report should be removed from this type.
