### ISSUE TITLE
Update Documentation links to Github

### ISSUE THREAD

**Issue by olzama** [delph-in/matrix#605]
The moinmoin MatrixDoc pages are still up and readable however some of them may be updated in the future and so the website should probably point to new, Github, pages. E.g. the https://matrix.ling.washington.edu/customize/matrix.cgi?subpage=toolbox-import page should point to https://github.com/delph-in/docs/wiki/MatrixDoc_ImportToolboxLexicon instead of http://moin.delph-in.net/wiki/MatrixDoc/ImportToolboxLexicon .

**Comment by goodmami** [comment]
Also links in the README. Searching this repo for "moin" turns up a few others: https://github.com/delph-in/matrix/search?q=moin
