### ISSUE TITLE
Updating Matrix web questionnaire site without a patas account?

### ISSUE THREAD

**Issue by olzama** [delph-in/matrix#606]
Currently, the Matrix web questionnaire lives on patas. To update it, one needs a patas account. To have a patas account, one typically needs to be a UW employee or student, though perhaps that is not a requirement? Like the matrixdev group; that includes non-uw people; are they able to copy files to patas?

I am going to lose my UW account soon; presumably I will lose my patas access at the same time? (I am not really sure). In that case, is the plan that I rely on someone else to copy any updated version of the questionnaire to patas or is the plan that I keep access somehow? (Either way is fine with me; if I lose access, I may need to eventually figure out how to set up local instances for testing, but that's a separate matter.)

@bmgraves @emilymbender

**Comment by emilymbender** [comment]
We can (and do!) provide patas accounts to non-UW collaborators. So, no worries about losing your account while you are an active Matrix developer :)

**Comment by dantiston** [comment]
I still have my UW account from undergrad. Did you get a notification that yours is going away?

But, more to the question, I agree, it would be good to have this option.

**Comment by olzama** [comment]
> I still have my UW account from undergrad. Did you get a notification that yours is going away?

Perhaps I am confused. I am pretty sure some things are going away but I am not sure which ones. Maybe I will never lose patas account unless someone removes me manually (that would be nice). 

I know they do take away some things though, like perhaps the Google drive and the write access to email?

**Comment by goodmami** [comment]
> I am pretty sure some things are going away but I am not sure which ones.

You'll lose the Google suite and any hosting the university provides, but not things that the ling department provides (unless they remove it separately). I'll send an email with some more info since it's not really a matrix issue.
