### ISSUE TITLE
customization questionnaire inaccessible

### ISSUE THREAD

**Issue by leoalenc** [delph-in/matrix#608]
Hi! I've just tried to access the customization questionnaire at https://matrix.ling.washington.edu/customize/matrix.cgi, but received a "500 internal server error" message:

> Internal Server Error
> The server encountered an internal error or misconfiguration and was unable to complete your request.
> 
> Please contact the server administrator at root@localhost to inform them of the time this error occurred, and the actions you performed just before this error.
> 
> More information about this error may be available in the server error log.

**Comment by olzama** [comment]
I suspect @bmgraves  may be investigating an issue, and so perhaps the questionnaire is temporarily inaccessible. But if not, then thanks for reporting!

You can use https://matrix.ling.washington.edu/trunktest/matrix.cgi in the meantime ;) it's the same version.

**Comment by leoalenc** [comment]
> I suspect @bmgraves may be investigating an issue, and so perhaps the questionnaire is temporarily inaccessible. But if not, then thanks for reporting!
> 
> You can use https://matrix.ling.washington.edu/trunktest/matrix.cgi in the meantime ;) it's the same version.

@olzama, thanks. This alternative version will be a big help, since the other one continues off-line.

**Comment by bmgraves** [comment]
/customize should be back up now. Not sure what brought it down. Thanks for
letting me know.

**Comment by olzama** [comment]
Thanks, Brandon!!
