### ISSUE TITLE
button for adding forbid constraints in determiners section not working 

### ISSUE THREAD

**Issue by leoalenc** [delph-in/matrix#611]
I've been updating my PorGram grammar for Portuguese and stepped into what seems to be an error in the questionnaire in the determiners section of the lexicon. I've tried to add some forbid constraints to model determiner inflection, but clicking on the "Add Forbid constraint" button displayed the message "Determiner 9
 requires one of the following position classes", the same message that is shown when clicking on the "Add Require constraint" button. I've just verified the verb section and this functionality is working fine there. See screen capture:

![forbid constraint](https://user-images.githubusercontent.com/1275848/127557411-928ba4d3-f67b-409a-9c6d-57e9cb5ed65e.png)

**Comment by emilymbender** [comment]
Thanks for reporting this. It appears that the problem is primarily cosmetic: If you fill in something under the forbid constraint, it should get recorded in the choices file as a "forbid" constraint, despite what the UI says.

**Comment by olzama** [comment]
Thanks for reporting! I fixed the cosmetic issue. The webpage should now display the correct text in this instance. (P.S.: I hope my updating the site didn't bring it down; for me it is working now.)
