### ISSUE TITLE
how to use the customize.py code

### ISSUE THREAD

**Issue by arademaker** [delph-in/matrix#616]
> The purpose of the `install` script is to set up a web server instance of the Matrix. If you just want to run customization from the command line, it is enough to have the source code and invoke customize.py. Did you need a local web instance for some reason?

_Originally posted by @emilymbender in https://github.com/delph-in/matrix/issues/614#issuecomment-921304524_

**Comment by arademaker** [comment]
I didn't know that. I found one reference to customize.py in https://github.com/delph-in/docs/wiki/MatrixDevTop. It seems that the main code is/was `matrix.py`, but I have to read it more carefully. But if I got it right, the command line script needs a choice file, right? How can we create the choice file without the web interface? 

In my [docker image](https://github.com/LR-POR/delphin-docker), I cloned this repo to `/tmp/` and installed the matrix in `/var/www/matrix`. The location `/var/www/matrix/gmcs/customize.py` is not the best one to expose to users of the docker... so maybe I need to better understand the architecture of the system.  Perhaps the best approach is to install the code that can be executed from the console in `/usr/local/matrix/` and keep the web part in `/var/www/matrix/` with references or symbolic links to `/usr/local/matrix`?

**Comment by goodmami** [comment]
Right, for running the above commands, you don't need to run the install script at all. You just need the Matrix source code and some dependencies satisfied:

```console
$ git clone https://github.com/delph-in/matrix.git
[...]
$ python3 -m venv env
$ source env/bin/activate
$ pip install -r requirements.txt
```

> But if I got it right, the command line script needs a choice file, right? How can we create the choice file without the web interface?

I actually gave an example of this in the [*Grammar development, test suites and profiles*](https://delphinqa.ling.washington.edu/t/grammar-development-test-suites-and-profiles/692/6) thread of the discourse site. You don't normally invoke `customize.py` directly, although you can. Instead, `matrix.py` is a bit more flexible and informative (try `python3 matrix.py --help`).

You can customize a grammar from a choices file like this:

```console
$ python matrix.py c choices
```

It will create a directory under the current directory named with the ISO code containing the grammar. You can also give a second argument:

```console
$ python matrix.py c choices dir
```

In this case, `dir` is the name of a directory (created if necessary) where the grammar directory will be created, in case you want to specify exactly where it will be written.

**Comment by arademaker** [comment]
Hi @goodmami, 

So the instructions [here](https://github.com/delph-in/matrix/blob/c327e0a32d9565453c41187f08724c865cf2b22f/CONTRIBUTING.md) are outdated?

For creating the choices file one still need the web interface, right? My idea is to have the docker as one alternative to the current [VirtualBox environment](https://wiki.ling.washington.edu/bin/view.cgi/Main/KnoppixLKB), that is, given a grammar engineer or a NLP developer the full range of DELPH-In tools.

**Comment by goodmami** [comment]
> So the instructions here are outdated?

That's a safe assumption. They are very old instructions.

> For creating the choices file one still need the web interface, right?

My apologies, I misread your question the first time. Yes, if you need to create a choices file (and not just a grammar *from* a choices file), then you'll need to use the questionnaire (web interface). Well, I guess you *could* create/edit it by hand, but then it's hard to tell if you've made a mistake.

**Comment by emilymbender** [comment]
In general, yes, to get a well-formed choices file, you'll need to go through the web questionnaire. Once you are tinkering with the morphological and lexical components, however, there are times when it is more convenient to edit by hand. In order to get a well-formedness check, I believe you can invoke validate.py.

... as for creating a docker, I can't work out a scenario where one would benefit from a local installation of the web questionnaire, though. Why not just access the one online?

**Comment by arademaker** [comment]
> ... as for creating a docker, I can't work out a scenario where one would benefit from a local installation of the web questionnaire, though. Why not just access the one online?

The system has been down a few times in the last few months... See #609 and #608. Moreover, the system is much more responsive if running locally. 

My docker was updated. It would be nice some cleanup of the current documentation of Matrix. Maybe removing the file CONTRIBUTING.md with outdated instructions and copying the @goodmami instructions above and from [Grammar development, test suites and profiles thread](https://delphinqa.ling.washington.edu/t/grammar-development-test-suites-and-profiles/692/6) to [MatrixTop](https://github.com/delph-in/docs/wiki/MatrixTop)? @emilymbender, I made some changes of links, [see here](https://github.com/delph-in/docs/wiki/MatrixTop/_compare/077c4cac0ad663c29316256e94f875f3a6f6487a...01882076076f7a45a5e05df7fb3d13ac80793525), hope that this improved the documentation a little bit.

**Comment by leoalenc** [comment]
> In general, yes, to get a well-formed choices file, you'll need to go through the web questionnaire. Once you are tinkering with the morphological and lexical components, however, there are times when it is more convenient to edit by hand. In order to get a well-formedness check, I believe you can invoke validate.py.
> 
> ... as for creating a docker, I can't work out a scenario where one would benefit from a local installation of the web questionnaire, though. Why not just access the one online?

@emilymbender , I would like to add an additional reason to run the customization system  locally, besides the ones pointed out by @arademaker.  In the last months 6 months or so, I've intensely used the system to implement grammar fragments of different sizes of diverse languages, including our Portuguese grammar. It is our goal to explore all functionalities of the system before resorting to hand-coding. However, in many occasions, the options I had inputted got lost!  It is really very laborious to frequently save the options to disk to prevent data loss.
