### ISSUE TITLE
Validate for nouny features on verby morphology

### ISSUE THREAD

**Issue by emilymbender** [delph-in/matrix#623]
We should give validation warnings (at least) when the user tries to say that "person = 3rd" on a verb or auxiliary.

**Comment by ltxom** [comment]
I see there are [code snippets in the lexicon.py](https://github.com/delph-in/matrix/blob/trunk/gmcs/linglib/lexicon.py#L1045-L1057) that implemented this validation:

```
index_features = set(['person', 'number', 'gender'])
```
```
if lextype in ('verb', 'adj', 'cop'):
        ...
	elif feat.get('head') in ('verb', 'adj', 'cop'):
		if feat.get('name') in index_features:
			mess = 'This feature is associated with nouns. ' + \
				   'Please select one of the NP options to use this feature.'
			vr.err(feat.full_key + '_head', mess)
```

If PNG features are specified on verb, adj, or cop, it shows an error message. This logic can also apply to aux, but a comment says, "lap: 1/5/11 removed aux to get rid of overzealous validation." However, I think PNG features cannot apply to auxiliary, so we should block it as well?

Also, should we add 'case' into index_features other than PNG?

**Comment by emilymbender** [comment]
Yes, I suspect that whatever was "overzealous" back then isn't anymore. (Though maybe we'll find out!)

Where else is the variable index_features used? It's not correct to call CASE an `index_features` (it doesn't appear on _ref-ind_), so it might be better to invoke CASE separately (as in check the union of `index_features` and {CASE}).

**Comment by ltxom** [comment]
I got it! I will add aux back to the checklist.

The variable `index_features` is only used to check if the feature in this set is associated with nouns. But for clarity purposes, I will check CASE separately.

**Comment by emilymbender** [comment]
Sounds good!

**Comment by ltxom** [comment]
This issue can be closed :)
