### ISSUE TITLE
poss lex rules don't copy up non-local values

### ISSUE THREAD

**Issue by emilymbender** [delph-in/matrix#625]
Lexical rules produced by the adnominal possession library seem to inherit from just lex-rule (rather than same-non-local-lex-rule) leading to 'leaks' when the grammar also has non-local features in use (such as with wh questions).

**Comment by olzama** [comment]
I thought I fixed a good deal of those... Did you keep a list of the ones you noticed? It could be helpful to add them here because otherwise someone might once again miss them (I did specifically try to go over that entire library and fix this, back in the day, I think).

**Comment by emilymbender** [comment]
Related: the adpositions contributed by the adnominal possession library also leave NON-LOCAL underspecified. Relevant choice to repro:

section=adnom-poss
  poss-strat1_order=head-final
  poss-strat1_mod-spec=spec
  poss-strat1_mark-loc=possessor
  poss-strat1_pronoun-allow=no
  poss-strat1_possessor-type=non-affix
  poss-strat1_possessor-mark-order=head-final
    poss-strat1_dep-comp-feat1_name=pernum
    poss-strat1_dep-comp-feat1_value=min
  poss-strat1_possessor-agr=non-agree
  poss-strat1_possessor-orth=jina
  poss-strat2_order=head-final
  poss-strat2_mod-spec=spec
  poss-strat2_mark-loc=possessor
  poss-strat2_pronoun-allow=no
  poss-strat2_possessor-type=non-affix
  poss-strat2_possessor-mark-order=head-final
    poss-strat2_dep-comp-feat1_name=pernum
    poss-strat2_dep-comp-feat1_value=aug
  poss-strat2_possessor-agr=non-agree
  poss-strat2_possessor-orth=jirra

**Comment by Diana-BZ** [comment]
Is this fixed with the changes made for [Issue 632](https://github.com/delph-in/matrix/issues/632)?

**Comment by emilymbender** [comment]
It's related but different -- 632 was looking at a phrase structure rule from the adnom poss library; this one concerns a lexical rule.

**Comment by ajcassell** [comment]
1. What is NON-LOCAL supposed to be rather than unspecified?
2. Regarding the original intent of this issue, I used the choices you provided and am not seeing lex-rule inherited by any other lexical rules explicitly.

**Comment by emilymbender** [comment]
1. Is there still a type like non-local-none? 
2. Perhaps that part has been fixed.

**Comment by ajcassell** [comment]
Yes, there is a non-local-none. Is this how you expect the NON-LOCAL should be?
 <img width="686" alt="Screen Shot 2024-11-14 at 5 00 12 PM" src="https://github.com/user-attachments/assets/4bb244e5-1674-42b4-8cee-e425153eaef3">

**Comment by emilymbender** [comment]
Yes.
