### ISSUE TITLE
extracted-det-phrase in rules.tdl but not my-language.tdl

### ISSUE THREAD

**Issue by emilymbender** [delph-in/matrix#626]
I have a couple of grammars in 567 this year with this line in rules.tdl:

`ex-det := extracted-det-phrase.`

... but extracted-det-phrase isn't defined anywhere. The LKB is happy to load these grammars but ace won't compile them. These choices snippets might be relevant:

```
section=word-order
word-order=free
has-dets=yes
noun-det-order=det-noun
has-aux=no

section=wh-q
front-matrix=single
matrix-front-opt=none-oblig
```

and

```
section=word-order
word-order=ovs
has-dets=yes
noun-det-order=noun-det

section=wh-q
front-matrix=single
matrix-front-opt=single-oblig
pied-pip=on
pied-pip-adp=on
```

I don't want to post the full choices files publicly, but can share them by email. (And for my own notes. this is lab4 from 567 in 2021, arp and hix.)

**Comment by ajcassell** [comment]
I believe this is resolved: https://github.com/delph-in/matrix/commit/8ca3f60cdab2494a0419afcf48712a05a25253ce

I am also seeing that this behavior is correct now where both extracted-det-phrase and ext-det must be included in the grammar together.
