### ISSUE TITLE
NON-LOCAL underspecified on clausal mod adverb heads

### ISSUE THREAD

**Issue by emilymbender** [delph-in/matrix#630]
This combination of choices:

```
section=wh-q
front-matrix=in-situ

section=clausalmods
  cms1_position=before
  cms1_modifier-attach=s
  cms1_subordinator=free
  cms1_subposition=after
  cms1_subordinator-type=head
  cms1_adverb-attach=s
    cms1_freemorph1_orth=alan
    cms1_freemorph1_pred=_because_v_rel
```

Produces adpositions with underspecified NON-LOCAL values, giving spurious ambiguity where the wh-in-situ rule is firing where it shouldn't.

**Comment by Diana-BZ** [comment]
Is this the same issue as [708](https://github.com/delph-in/matrix/issues/708)?

**Comment by emilymbender** [comment]
Yes, I think so.
