### ISSUE TITLE
Clausal mods library needs to be aware of NON-LOCAL

### ISSUE THREAD

**Issue by emilymbender** [delph-in/matrix#635]
"after-prehead-modifying-clause-phrase" and the like should inherit from "unary-nonloc-phrase" (at least) to avoid spurious application of extraction rules below them. (Ex: hix lab8 from 567 WI 2022)

**Comment by emilymbender** [comment]
Better to put it on the supertype: morphological-subord-clause-phrase

**Comment by Diana-BZ** [comment]
Do you mean to put: morphological-subord-clause-phrase as a supertype of after-prehead-modifying-clause-phrase?

**Comment by Diana-BZ** [comment]
Does 'unary-nonloc-phrase' need to be a supertype of both? Or did you want it on just 'morphological-subord-clause-phrase'?

**Comment by emilymbender** [comment]
Just on morphological-subord-clause-phrase, I think should do it.

**Comment by ajcassell** [comment]
@emilymbender This appears to be done, so I think it can be closed. 
`supertype = 'morphological-subord-clause-phrase'
        mylang.add(supertype + ' := unary-phrase & unary-nonloc-phrase &\
    [ SYNSEM [ LOCAL [ CAT [ MC -,\
                            VAL [ SUBJ #subj,\
                                  SPR < >,\
                                   SPEC < >,\
                                  COMPS < > ],\
                            HEAD adp & [ MOD < [ LOCAL scopal-mod &\
  						[ CAT [ HEAD verb,\
  							VAL [ SPR < >,\
  							      COMPS < > ]],\
  						  CONT.HOOK [ LTOP #mcl,\
  								INDEX #index ]]] > ]],\
etc`

**Comment by emilymbender** [comment]
Thank you. Closing.
