### ISSUE TITLE
nominalization-lex-rule underspecified for NON-LOCAL

### ISSUE THREAD

**Issue by emilymbender** [delph-in/matrix#705]
Lots of extra ambiguity in grammars with wh questions and nominalization, because high-or-mid-nominalization-lex-rule doesn't inherit from same-non-local-lex-rule.

**Comment by ajcassell** [comment]
high-or-mid-nominalization-lex-rule no longer exists since Keren's changes. I'm not sure if we need this issue anymore of it is relevant in a different area of the code.

**Comment by emilymbender** [comment]
Let's say ok for now!
