### ISSUE TITLE
Extra copy of adj-head-int

### ISSUE THREAD

**Issue by emilymbender** [delph-in/matrix#717]
The attached choices file leads to a grammar with two separate instantiations of adj-head-int-phrase (one called adj-head and one called adj-head-int). This obviously leads to undesirable ambiguity.
[hadj-int-choices.txt](https://github.com/delph-in/matrix/files/14530431/hadj-int-choices.txt)

**Comment by ajcassell** [comment]
@emilymbender is adj-head-int different from adj-head? Does it suffice to change the instantiation to say adj-head-int := instead of adj-head := or do they represent different things? I tried that and all the regression tests passed.

**Comment by emilymbender** [comment]
The adj-head rules that are instantiated should all inherit from either the "intersective" or "scopal" types. I don't know if that grammar had something that was inheriting from an underspecified supertype, or actually just had effectively two copies of the same rule.

**Comment by ajcassell** [comment]
The rules were both inheriting from the same adj-head-int-phrase supertype nothing else, so I believe that makes them just duplicates.

**Comment by emilymbender** [comment]
Ok! Then we just want one and it should be called adj-head-int.
